### PR TITLE
Pull ckesoglou fork of Develop with reformatting

### PR DESCRIPTION
**Pull request by ckesoglou**
Please take a look at this significant overhaul and reformatting / refactoring attempt and leave your comments.

This is in preparation of the final pdf generation of this report.

### CODE REVIEW

**Review by vkumar12180 — APPROVED** [review]
Looks good!

**Comment by sassaf01** [comment]
Having a look through everything, I think this looks really amazing - you've done a great job Chris!! :)) Ready to submit!!

**Review by sassaf01 — APPROVED** [review]
Forgot to review! Approve all of these changes!

**Comment by ckesoglou** [comment]
With 2/3 approvals (and the fact that this is still merging into a _development_ branch (not master), I believe this is okay to merge without waiting for @Daniel832001

**Pull request merged**
