### PR TITLE
Added HMW statements for Customers & System Admin

### PR DESCRIPTION
**Pull request by ckesoglou**

### CODE REVIEW

**Comment by sassaf01** [comment]
Looks good to me!

**Comment by vkumar12180** [comment]
Looks amazing.

**Review by vkumar12180 — APPROVED** [review]
looks great

**Review by sassaf01 — CHANGES_REQUESTED** [review]
Add your date of editing into Empathy Charts!

**Review by Daniel832001 — APPROVED** [review]

**Review by sassaf01 — APPROVED** [review]

**Pull request merged**
